image:
  file: Dockerfile
tasks:
  - init: mkdir logs && cd build && . ./scripts/install_prereq.sh
    command: export PATH=$PATH:/workspace/LiquiDOS/build/toolchain/cross/x86_64/bin/

vscode:
  extensions:
    - webfreak.debug@0.24.0:1zVcRsAhewYEX3/A9xjMNw==
    - basdp.language-gas-x86@0.0.1:/cY7lTwZoMr2J0aZZLH1IQ==
    - 13xforever.language-x86-64-assembly@2.2.11:KHifVlvO7IZEEb1l8RDq1Q==
    - ms-vscode.cpptools@0.26.2:TkbJMXArQ9iIo9ySZRerdQ==
    - PKief.material-icon-theme@3.9.2:xeHlNzPEF04yFqz/xKCD5w==
    - thenikso.github-plus-theme@1.2.1:2syO2dRk6EVbHHN8ezXTmA==